Add codacy support
IndigoUnited/node-detect-readme-badges pull request #46
Opened 2018-05-07 20:27 UTC by Ffloriel

## Proposed changes

Add codacy support:
- Code quality grade
- Code Coverage

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

I am not sure about some of the changes that I made concerning the codacy badges. I put the name of the type for the code quality grade as `grade`. This seems to be how codacy reference it in their url. Shields.io seems to use `code quality`. Which one would be better?

Codacy has two badges: coverage and code quality. should the type be added to the modifiers object? or would it be repetitive with the `type` property?

2018-05-09 14:19 UTC, zebateira requested changes
> I am not sure about some of the changes that I made concerning the codacy badges. I put the name of the type for the code quality grade as grade. This seems to be how codacy reference it in their url. Shields.io seems to use code quality. Which one would be better?

I'd say `quality`. What do you think @satazor ?

> Codacy has two badges: coverage and code quality. should the type be added to the modifiers object? or would it be repetitive with the type property?

Yeah, the type should go to the modifiers object, but what do you mean by `repetitive with the type property`?

/cc @satazor

2018-05-09 14:19 UTC, carsy commented on lib/codacy.js
> +    const upperCaseFirstLetter = str => `${str.charAt(0).toUpperCase()}${str.substr(1)}`;
Could you move this to `lib/util`?

2018-05-16 21:47 UTC, Ffloriel commented
@carsy the info object currently give something like this:
```
info: {
    service: 'codacy',
    type: 'coverage',
    modifiers: { branch: undefined }
}
```
so with the type in `modifiers`:
```
info: {
    service: 'codacy',
    type: 'coverage',
    modifiers: {
        branch: undefined,
        type: 'coverage'
    }
}
```
but it makes sense to add it to `modifiers` object

2018-05-17 09:10 UTC, satazor commented
@carsy I would say that it's two types: 'coverage' and 'quality'. There's no need to have repetitive type inside the modifiers.

2018-05-23 16:50 UTC, carsy commented
I agree with @satazor.
@Ffloriel could you change `grade` to `quality` then?

2018-05-31 20:18 UTC, Ffloriel commented
Sorry for the late reply. Yes, I can change it

2018-06-02 18:11 UTC, carsy commented
@Ffloriel looks good!

/cc @satazor

2018-08-03 17:23 UTC, Ffloriel commented
@satazor @carsy is there anything left to change for this PR?

2018-08-04 10:26 UTC, carsy commented
@Ffloriel I'm sorry for the late reply! I'll just nudge @satazor to see if he has anything to add. If not, then we're golden :)

2018-08-04 12:25 UTC, merged

2018-08-04 12:26 UTC, satazor commented
Thanks so much and sorry for the delays!

2018-08-04 12:26 UTC, satazor commented
@carsy can you release a new version? I think it would be a minor in this cass

2018-08-05 05:35 UTC, carsy commented
@Ffloriel @satazor published!